#!/usr/bin/env bash
# scripts/render-env.sh
# Renders .env.prod atomically from environment variables.
# Called by the deploy.yml SSH job — all required vars are passed as env.
#
# Usage (called from deploy.yml heredoc or directly):
#   export DATABASE_URL=... COOKIE_SECRET=... <other vars>
#   bash scripts/render-env.sh [/opt/stremingchat/.env.prod]
#
# First argument is the output path (default: /opt/stremingchat/.env.prod).
# File is written atomically (tmp + mv) and chmod 600.
set -euo pipefail

OUTPUT_PATH="${1:-/opt/stremingchat/.env.prod}"

# ─── Validate required vars ───────────────────────────────────────────────────
required=(
  DATABASE_URL
  COOKIE_SECRET
  GEMINI_API_KEY
  LANGFUSE_PUBLIC_KEY
  LANGFUSE_SECRET_KEY
  LANGFUSE_SALT
  LANGFUSE_ENCRYPTION_KEY
  LANGFUSE_DB_PASSWORD
  LANGFUSE_NEXTAUTH_SECRET
  LANGFUSE_NEXTAUTH_URL
  POSTGRES_PASSWORD
  CLICKHOUSE_PASSWORD
  REDIS_PASSWORD
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
  BACKEND_IMAGE_TAG
  FRONTEND_IMAGE_TAG
)

missing=()
for var in "${required[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    missing+=("$var")
  fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "ERROR: The following required environment variables are missing:" >&2
  for m in "${missing[@]}"; do
    echo "  - $m" >&2
  done
  exit 1
fi

# ─── Atomic write ─────────────────────────────────────────────────────────────
# Write to a temp file first, then mv (atomic on same filesystem).
# This prevents a partially-written .env.prod from being read mid-write.
tmpfile=$(mktemp "$(dirname "$OUTPUT_PATH")/.env.prod.XXXXXX")
trap 'rm -f "$tmpfile"' EXIT

cat > "$tmpfile" <<EOF
# Generated by scripts/render-env.sh — DO NOT EDIT MANUALLY
# Source of truth: GitHub Actions secrets → deploy.yml → this file
NODE_ENV=${NODE_ENV:-production}
HOST_HAS_TLS=${HOST_HAS_TLS:-true}

# Application
DATABASE_URL=${DATABASE_URL}
COOKIE_SECRET=${COOKIE_SECRET}
GEMINI_API_KEY=${GEMINI_API_KEY}
PUBLIC_URL=${PUBLIC_URL:-}

# Image tags (set by CI to sha-<commit>)
BACKEND_IMAGE_TAG=${BACKEND_IMAGE_TAG}
FRONTEND_IMAGE_TAG=${FRONTEND_IMAGE_TAG}

# Postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Langfuse
LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
LANGFUSE_SALT=${LANGFUSE_SALT}
LANGFUSE_ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
LANGFUSE_DB_PASSWORD=${LANGFUSE_DB_PASSWORD}
LANGFUSE_NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
LANGFUSE_NEXTAUTH_URL=${LANGFUSE_NEXTAUTH_URL}
LANGFUSE_HOST=http://langfuse-web:3000

# ClickHouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# MinIO
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
EOF

chmod 600 "$tmpfile"
mv "$tmpfile" "$OUTPUT_PATH"

# Suppress trap since mv succeeded
trap - EXIT

echo "✓ .env.prod rendered atomically at ${OUTPUT_PATH}" >&2
